name: Build and publish Docker images to ghcr.io

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # every day
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        run: make docker-login LOGIN_USER=${{ github.actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build a Docker image for Python ${{ matrix.python-version }}
        run: make docker-build PYTHON_VERSION=${{ matrix.python-version }}

      - name: Push a Docker image for Python ${{ matrix.python-version }}
        run: make docker-push PYTHON_VERSION=${{ matrix.python-version }}
